# Generated by Django 4.1 on 2022-09-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartproduct_app', '0005_alter_cart_owner'),
        ('customer_app', '0003_order_customer_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartproduct_app.cart', verbose_name='Cart'),
        ),
    ]
