# Generated by Django 4.1 on 2022-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
