# Generated by Django 4.1 on 2022-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Display type')),
                ('resolution', models.CharField(max_length=255, verbose_name='Screen resolution')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Battery capacity')),
                ('ram', models.CharField(max_length=255, verbose_name='Ram')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Maximum built-in memory')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Main camera')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Front camera')),
            ],
        ),
    ]
