# Generated by Django 4.1 on 2022-08-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
        ('smartphones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='category_app.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(default=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=9, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='slug',
            field=models.SlugField(default=True, unique=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='title',
            field=models.CharField(default=True, max_length=255, verbose_name='Title'),
        ),
    ]
