# Generated by Django 4.1 on 2022-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones_app', '0003_alter_smartphone_sd_alter_smartphone_sd_volume_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maximum SD card memory'),
        ),
    ]
