# Generated by Django 4.1 on 2022-09-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartproduct_app', '0002_cart_for_anonymous_user_cart_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='cartproduct_app.cartproduct'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='cartproduct_app.cart', verbose_name='Cart'),
        ),
    ]
