# Generated by Django 4.1 on 2022-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartproduct_app', '0003_alter_cart_products_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total price'),
        ),
    ]
