# Generated by Django 4.1 on 2022-09-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
        ('cartproduct_app', '0004_alter_cart_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer', verbose_name='Owner'),
        ),
    ]
