# Generated by Django 4.1 on 2022-09-27 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category_app', '0004_rename_favorites_product_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
