# Generated by Django 4.1 on 2022-09-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_product'),
        ('notebooks_app', '0002_notebook_category_notebook_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='title',
        ),
        migrations.AddField(
            model_name='notebook',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category_app.product'),
            preserve_default=False,
        ),
    ]
