# Generated by Django 4.1 on 2022-09-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_alter_reviews_options_reviews_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Photo_review')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_review', to='reviews_app.reviews')),
            ],
            options={
                'verbose_name': 'Photo review',
                'verbose_name_plural': 'Photo review',
            },
        ),
    ]
