# Generated by Django 4.1 on 2022-09-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_imagereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_reviews', models.ImageField(blank=True, upload_to='')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_app.reviews')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageReview',
        ),
    ]
