# Generated by Django 4.1 on 2022-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0006_remove_reviews_file_reviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
