# Generated by Django 4.1 on 2022-10-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0009_alter_reviews_options_remove_reviews_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_review', models.ImageField(blank=True, upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews_app.reviews')),
            ],
        ),
    ]
